dist: trusty
sudo: false
language: node_js
node_js:
  - 12.14.1
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  directories:
    - $HOME/.npm
branches:
  only:
    - master
    - develop
install:
  - npm i -g npm@6.9.0
  - npm ci
script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox